'use strict';

exports.BattleLearnsets = {
	///////////////////////////////////
	// Prism Fakemon
	///////////////////////////////////
	phancero: {learnset: {
		acidarmor: ["3L30"],
		agility: ["3L20"],
		airslash: ["3L90"],
		ancientpower: ["3M"],
		attract: ["3M"],
		bodyslam: ["3M"],
		bulkup: ["3M"],
		counter: ["3M"],
		curse: ["3M"],
		cut: ["3M"],
		darkpulse: ["3M"],
		defensecurl: ["3M"],
		dig: ["3M"],
		doubleedge: ["3M"],
		doubleteam: ["3M"],
		dragonbreath: ["3M"],
		dragonclaw: ["3M"],
		earthquake: ["3M"],
		endure: ["3M"],
		energyball: ["3M"],
		fireblast: ["3M"],
		flamethrower: ["3M"],
		flash: ["3M"],
		flashcannon: ["3M"],
		frustration: ["3M"],
		gust: ["3L7"],
		headbutt: ["3M"],
		hiddenpower: ["3M"],
		highjumpkick: ["3L100"],
		hyperbeam: ["3M"],
		hypervoice: ["3M"],
		ironhead: ["3M"],
		irontail: ["3M"],
		leechseed: ["3L35"],
		lick: ["3L10"],
		metronome: ["3M"],
		mudslap: ["3M"],
		poisonjab: ["3M"],
		pound: ["3L1"],
		protect: ["3M"],
		raindance: ["3M"],
		rest: ["3M"],
		return: ["3M"],
		rockslide: ["3M"],
		rocksmash: ["3M"],
		safeguard: ["3M"],
		sandstorm: ["3M"],
		shadowball: ["3L40"],
		shadowclaw: ["3L80", "3M"],
		signalbeam: ["3M"],
		skyattack: ["3L50"],
		sleeptalk: ["3M"],
		sludgebomb: ["3M"],
		solarbeam: ["3M"],
		strength: ["3M"],
		substitute: ["3M"],
		sunnyday: ["3M"],
		surf: ["3M"],
		swagger: ["3M"],
		swift: ["3M"],
		swordsdance: ["3M"],
		teleport: ["3L4"],
		thief: ["3M"],
		thunder: ["3M"],
		thunderbolt: ["3M"],
		toxic: ["3M"],
		triattack: ["3L95", "3M"],
		waterfall: ["3M"],
		watergun: ["3L15", "3L60"],
		willowisp: ["3M"],
		wingattack: ["3L25"],
		wrap: ["3L70"],
	}},
	
	///////////////////////////////////
	// Gen 1 Glitchmon
	///////////////////////////////////
	rb202: {learnset: {
		absorb: ["3L126", "3L144"],
		aurorabeam: ["3L32"],
		barrage: ["3L1"],
		bide: ["3M"],
		bodyslam: ["3M"],
		clamp: ["3L1"],
		counter: ["3M"],
		doubleslap: ["3L254"],
		doubleteam: ["3M"],
		fissure: ["3M"],
		flash: ["3L250"],
		fly: ["3L114"],
		highjumpkick: ["3L1"],
		horndrill: ["3L167"],
		hyperbeam: ["3M"],
		icebeam: ["3M"],
		karatechop: ["3L40"],
		leechlife: ["3L1"],
		leechseed: ["3L234"],
		megadrain: ["3M"],
		metronome: ["3M"],
		pound: ["3L225"],
		psychic: ["3M"],
		razorwind: ["3M"],
		reflect: ["3M"],
		rockslide: ["3M"],
		sandattack: ["3L1"],
		selfdestruct: ["3M"],
		skullbash: ["3M"],
		skyattack: ["3M"],
		slam: ["3L11", "3L205"],
		superglitch00: ["3L28", "3L62"],
		superglitcha7: ["3L207"],
		surf: ["3M"],
		swordsdance: ["3L9"],
		tackle: ["3L204", "3L229"],
		thunderbolt: ["3M"],
		tm05: ["3L119", "3L163"],
		tm07: ["3L145", "3L146", "3L148", "3L185"],
		tm09: ["3L30", "3L36", "3L99"],
		tm29: ["3L33"],
		tm34: ["3L241"],
		tm45: ["3L209"],
		tm50: ["3L19", "3L48"],
		triattack: ["3M"],
	}},
};
