'use strict';

exports.BattleLearnsets = {
	////////////////////////////////////
	// TPPLeague Fakemon
	////////////////////////////////////
	gumblegoose: {learnset: {
		acrobatics: ["7M"],
		aerialace: ["7M"],
		aquaring: ["7L17"],
		attract: ["7M"],
		aurasphere: ["7L31"],
		block: ["6T"],
		bulkup: ["7M"],
		calmmind: ["7M"],
		confide: ["7M"],
		cottonguard: ["7L23"],
		dazzlinggleam: ["7M"],
		dig: ["6M"],
		doubleteam: ["7M"],
		dragonpulse: ["7L29"],
		dragontail: ["7M"],
		drillrun: ["6T"],
		echoedvoice: ["7M"],
		endeavor: ["6T"],
		explosion: ["7M"],
		fireblast: ["7M"],
		flash: ["6M"],
		flashcannon: ["7M"],
		fling: ["7M"],
		fly: ["7M"],
		focuspunch: ["6T"],
		freezedry: ["7L36"],
		frustration: ["7M"],
		gastroacid: ["6T"],
		gigaimpact: ["7M"],
		gravity: ["6T"],
		gust: ["7L1"],
		hiddenpower: ["7M"],
		hurricane: ["7L65"],
		hyperbeam: ["7M"],
		icebeam: ["7M"],
		lightscreen: ["7L49"],
		mist: ["7L10"],
		originpulse: ["7L78"],
		outrage: ["6T"],
		poisonjab: ["7M"],
		psychic: ["7M"],
		psychup: ["7M"],
		quiverdance: ["7L57"],
		reflect: ["7L52"],
		return: ["7M"],
		rest: ["7M"],
		roar: ["7M"],
		rocksmash: ["6M"],
		roost: ["7L41", "7M"],
		safeguard: ["7M"],
		scald: ["7M"],
		shadowball: ["7M"],
		skillswap: ["6T"],
		sleeptalk: ["7M"],
		sludgebomb: ["7M"],
		stoneedge: ["7M"],
		strength: ["6M"],
		superfang: ["6T"],
		swagger: ["7M"],
		thief: ["7M"],
		thunderbolt: ["7M"],
		toxic: ["7M"],
		trickroom: ["7M"],
		watergun: ["7L1"],
		waterpulse: ["7L33"],
	}},
	
	unown: {learnset: {
		hiddenpower: ["7M", "7L1", "6L1", "5L1", "4L1", "3L1"],
		naturepower: ["7D"], // We're using Dream World moves, because idk why not?
		secretpower: ["7D"],
		superpower: ["7D"],
		ancientpower: ["7D"],
		cosmicpower: ["7D"],
		earthpower: ["7D"],
		trickroom: ["7D"],
		wonderroom: ["7D"],
		magicroom: ["7D"],
		prismaticlaser: ["7D"],
		psychic: ["7D"],
		psychicfangs: ["7D"],
		psychicterrain: ["7D"],
		mirrorcoat: ["7D"],
		
	}},
	swarmofunown: {learnset: {
		hiddenpower: ["7M", "7L1", "6L1", "5L1", "4L1", "3L1"],
		//TODO all Psychic moves
	}},
	
	///////////////////////////////////
	// Prism Fakemon
	///////////////////////////////////
	phancero: {learnset: {
		acidarmor: ["7L30"],
		agility: ["7L20"],
		airslash: ["7L90"],
		ancientpower: ["7M"],
		attract: ["7M"],
		bodyslam: ["7M"],
		bulkup: ["7M"],
		counter: ["7M"],
		curse: ["7M"],
		cut: ["7M"],
		darkpulse: ["7M"],
		defensecurl: ["7M"],
		dig: ["7M"],
		doubleedge: ["7M"],
		doubleteam: ["7M"],
		dragonbreath: ["7M"],
		dragonclaw: ["7M"],
		earthquake: ["7M"],
		endure: ["7M"],
		energyball: ["7M"],
		fireblast: ["7M"],
		flamethrower: ["7M"],
		flash: ["7M"],
		flashcannon: ["7M"],
		frustration: ["7M"],
		gust: ["7L7"],
		headbutt: ["7M"],
		hiddenpower: ["7M"],
		highjumpkick: ["7L100"],
		hyperbeam: ["7M"],
		hypervoice: ["7M"],
		ironhead: ["7M"],
		irontail: ["7M"],
		leechseed: ["7L35"],
		lick: ["7L10"],
		metronome: ["7M"],
		mudslap: ["7M"],
		poisonjab: ["7M"],
		pound: ["7L1"],
		protect: ["7M"],
		raindance: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		rockslide: ["7M"],
		rocksmash: ["7M"],
		safeguard: ["7M"],
		sandstorm: ["7M"],
		shadowball: ["7L40"],
		shadowclaw: ["7L80", "7M"],
		signalbeam: ["7M"],
		skyattack: ["7L50"],
		sleeptalk: ["7M"],
		sludgebomb: ["7M"],
		solarbeam: ["7M"],
		strength: ["7M"],
		substitute: ["7M"],
		sunnyday: ["7M"],
		surf: ["7M"],
		swagger: ["7M"],
		swift: ["7M"],
		swordsdance: ["7M"],
		teleport: ["7L4"],
		thief: ["7M"],
		thunder: ["7M"],
		thunderbolt: ["7M"],
		toxic: ["7M"],
		triattack: ["7L95", "7M"],
		waterfall: ["7M"],
		watergun: ["7L15", "7L60"],
		willowisp: ["7M"],
		wingattack: ["7L25"],
		wrap: ["7L70"],
	}},
	
	///////////////////////////////////
	// Gen 1 Glitchmon
	///////////////////////////////////
	rb202: {learnset: {
		absorb: ["7L126", "7L144"],
		aurorabeam: ["7L32"],
		barrage: ["7L1"],
		bide: ["7M"],
		bodyslam: ["7M"],
		clamp: ["7L1"],
		counter: ["7M"],
		doubleslap: ["7L254"],
		doubleteam: ["7M"],
		fissure: ["7M"],
		flash: ["7L250"],
		fly: ["7L114"],
		highjumpkick: ["7L1"],
		horndrill: ["7L167"],
		hyperbeam: ["7M"],
		icebeam: ["7M"],
		karatechop: ["7L40"],
		leechlife: ["7L1"],
		leechseed: ["7L234"],
		megadrain: ["7M"],
		metronome: ["7M"],
		pound: ["7L225"],
		psychic: ["7M"],
		razorwind: ["7M"],
		reflect: ["7M"],
		rockslide: ["7M"],
		sandattack: ["7L1"],
		selfdestruct: ["7M"],
		skullbash: ["7M"],
		skyattack: ["7M"],
		slam: ["7L11", "7L205"],
		superglitch00: ["7L28", "7L62"],
		superglitcha7: ["7L207"],
		surf: ["7M"],
		swordsdance: ["7L9"],
		tackle: ["7L204", "7L229"],
		thunderbolt: ["7M"],
		tm05: ["7L119", "7L163"],
		tm07: ["7L145", "7L146", "7L148", "7L185"],
		tm09: ["7L30", "7L36", "7L99"],
		tm29: ["7L33"],
		tm34: ["7L241"],
		tm45: ["7L209"],
		tm50: ["7L19", "7L48"],
		triattack: ["7M"],
	}},

	////////////////////////////////////
	// Touhoumon
	////////////////////////////////////
	chibisanae: {learnset: {
		attract: ["7M"],
		calmmind: ["7M"],
		decision: ["7L18", "7M"],
		defensecurl: ["7E", "6E", "5E", "4E", "3E"],
		doubleteam: ["7M"],
		foresight: ["7E", "6E", "5E", "4E", "3E"],
		gigadrain: ["7M"],
		grassknot: ["7L14"],
		growl: ["7L5"],
		mist: ["7E", "6E", "5E", "4E", "3E"],
		pound: ["7L1"],
		protect: ["7M"],
		raindance: ["7L27", "7M"],
		refresh: ["7E", "6E", "5E", "4E", "3E"],
		return: ["7M"],
		rest: ["7M"],
		safeguard: ["7M"],
		secretpower: ["7M"],
		skillswap: ["7M"],
		solarbeam: ["7M"],
		surf: ["7M"],
		swagger: ["7M"],
		taunt: ["7M"],
		tbodyslam: ["7E", "6E", "5E", "4E", "3E"],
		tflash: ["7M"],
		tforcepalm: ["7E", "6E", "5E", "4E", "3E"],
		tgust: ["7L9"],
		thunder: ["7M"],
		thunderwave: ["7E", "6E", "5E", "4E", "3E"],
		trazorwind: ["7L32", "7M"],
		waterpulse: ["7L23", "7M"],
		weatherball: ["7E", "6E", "5E", "4E", "3E"],
	}},
	sanae: {learnset: {
		attract: ["7M"],
		calmmind: ["7M"],
		decision: ["7M"],
		doubleteam: ["7M"],
		gigadrain: ["7M"],
		grassknot: ["7L1"],
		heatwave: ["7L50"],
		icywind: ["7L1"],
		ingrain: ["7L1"],
		mirrorcoat: ["7L1"],
		protect: ["7M"],
		psychup: ["7L1", "7L54"],
		raindance: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		safeguard: ["7M"],
		secretpower: ["7M"],
		skillswap: ["7M"],
		solarbeam: ["7M"],
		surf: ["7M"],
		swagger: ["7L43", "7M"],
		taeroblast: ["7L1", "7L58"],
		taunt: ["7M"],
		textrasensory: ["7L37"],
		tflash: ["7M"],
		thunder: ["7M"],
		trazorwind: ["7M"],
		tsilverwind: ["7L1", "7L62"],
		ttwister: ["7L40"],
		waterpulse: ["7M"],
		whirlwind: ["7L1", "7L46"],
		wish: ["7L1"],
	}},
	chibimomiji: {learnset: {
		attract: ["7M"],
		bladeflash: ["7L19"],
		brickbreak: ["7M"],
		bulldoze: ["7M"],
		counter: ["7E"],
		dig: ["7M"],
		doubleteam: ["7M"],
		earthquake: ["7M"],
		extremespeed: ["7E"],
		facade: ["7M"],
		focusenergy: ["7L8"],
		focuspunch: ["7M"],
		howl: ["7L15"],
		nightslash: ["7E"],
		protect: ["7M"],
		pursuit: ["7E"],
		rest: ["7M"],
		return: ["7M"],
		reversal: ["7E"],
		roar: ["7M"],
		secretpower: ["7M"],
		tailwhip: ["7L5"],
		tbite: ["7L12"],
		tcrunch: ["7E"],
		tcut: ["7M"],
		trage: ["7L26"],
		trazorwind: ["7L22", "7M"],
		tscratch: ["7L1"],
	}},
	momiji: {learnset: {
		attract: ["7M"],
		braver: ["7L1", "7L56"],
		brickbreak: ["7M"],
		bulldoze: ["7M"],
		dig: ["7M"],
		doubleteam: ["7M"],
		dragondance: ["7L40"],
		earthquake: ["7M"],
		endeavor: ["7L1"],
		endure: ["7L1", "7L34"],
		facade: ["7M"],
		focuspunch: ["7M"],
		heatclaw: ["7L1"],
		irondefense: ["7L1"],
		killingbite: ["7L1", "7L52"],
		nightslash: ["7L44"],
		protect: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		roar: ["7M"],
		rocksmash: ["7M"],
		secretpower: ["7M"],
		sleeptalk: ["7L1"],
		substitute: ["7L1"],
		swordsdance: ["7L1", "7L48"],
		tcrunch: ["7L37"],
		tcut: ["7M"],
		tfurycutter: ["7L31"],
		trage: ["7L1"],
		trazorwind: ["7M"],
	}},
	chibitokiko: {learnset: {
		agility: ["7L14"],
		attract: ["7M"],
		bellydrum: ["7E"],
		blizzard: ["7E"],
		dig: ["7M"],
		doubleteam: ["7L20", "7M"],
		endeavor: ["7L17"],
		facade: ["7M"],
		fireblast: ["7E"],
		flail: ["7E"],
		fly: ["7M"],
		focuspunch: ["7M"],
		heartbreak: ["7M"],
		helpinghand: ["7E"],
		mindbomb: ["7M"],
		peck: ["7L1"],
		protect: ["7M"],
		psychic: ["7M"],
		raindance: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		safeguard: ["7M"],
		sandattack: ["7L5"],
		secretpower: ["7M"],
		snatch: ["7M"],
		steelwing: ["7M"],
		sunnyday: ["7M"],
		swagger: ["7M"],
		tancientpower: ["7E"],
		tfakeout: ["7E"],
		thief: ["7M"],
		toxic: ["7M"],
		tquickattack: ["7L8"],
		trazorwind: ["7M"],
		tstomp: ["7L11"],
		twingattack: ["7L23"],
	}},
	tokiko: {learnset: {
		attract: ["7M"],
		dig: ["7M"],
		doubleteam: ["7M"],
		endeavor: ["7L1"],
		endure: ["7L1"],
		facade: ["7M"],
		fly: ["7M"],
		focuspunch: ["7M"],
		heartbreak: ["7M"],
		heatclaw: ["7L1"],
		mindbomb: ["7M"],
		mirrorcoat: ["7L1"],
		protect: ["7M"],
		psychic: ["7M"],
		psychup: ["7L1"],
		raindance: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		roost: ["7L36"],
		safeguard: ["7M"],
		screech: ["7L44"],
		secretpower: ["7M"],
		skyattack: ["7L1", "7L52"],
		sleeptalk: ["7L1"],
		snatch: ["7M"],
		soar: ["7L40"],
		steelwing: ["7M"],
		substitute: ["7L1"],
		sunnyday: ["7M"],
		swagger: ["7M"],
		tfuryswipes: ["7L30"],
		thief: ["7M"],
		torment: ["7L27"],
		toxic: ["7M"],
		trazorwind: ["7M"],
		tslash: ["7L48"],
		whirlwind: ["7L1"],
		zenheadbutt: ["7L33"],
	}},
	chibisatori: {learnset: {
		tmirrorshot: ["7L20"],
		transform: ["7L1"],
	}},
	satori: {learnset: {
		attract: ["7M"],
		calmmind: ["7M"],
		counter: ["7L1"],
		darkpulse: ["7L42"],
		decision: ["7M"],
		doubleteam: ["7M"],
		encore: ["7L1", "7L56"],
		feint: ["7L1"],
		focusblast: ["7M"],
		icebeam: ["7M"],
		ingrain: ["7L1"],
		jamming: ["7L1"],
		mindbomb: ["7M"],
		mirrorcoat: ["7L1"],
		nightshade: ["7L1"],
		protect: ["7M"],
		psychic: ["7L39", "7M"],
		psychoboost: ["7L1", "7L64"],
		psychup: ["7L1", "7L60"],
		rest: ["7M"],
		return: ["7M"],
		safeguard: ["7M"],
		secretpower: ["7M"],
		shadowball: ["7L48", "7M"],
		skillswap: ["7M"],
		solarbeam: ["7M"],
		substitute: ["7L1", "7L52"],
		thunderbolt: ["7M"],
		tsignalbeam: ["7L45", "7M"],
		willowisp: ["7M"],
	}},
	defensemomiji: {learnset: {
		attract: ["7M"],
		braver: ["7L1", "7L56"],
		brickbreak: ["7M"],
		bulldoze: ["7M"],
		dig: ["7M"],
		doubleteam: ["7M"],
		dragondance: ["7L44"],
		earthquake: ["7M"],
		endeavor: ["7L1"],
		endure: ["7L1"],
		facade: ["7M"],
		focuspunch: ["7M"],
		heatclaw: ["7L1"],
		irondefense: ["7L1"],
		killingbite: ["7L1", "7L52"],
		protect: ["7M"],
		spikes: ["7L48"],
		rest: ["7M"],
		return: ["7M"],
		revenge: ["7L40"],
		roar: ["7L34", "7M"],
		rocksmash: ["7M"],
		secretpower: ["7M"],
		sleeptalk: ["7L1"],
		substitute: ["7L1"],
		swordsdance: ["7L1"],
		tcrushclaw: ["7L37"],
		tcut: ["7M"],
		tfuryswipes: ["7L31"],
		trage: ["7L1"],
		trazorwind: ["7M"],
	}},
	attacktokiko: {learnset: {
		attract: ["7M"],
		bravebird: ["7L44"],
		dig: ["7M"],
		doubleteam: ["7M"],
		endeavor: ["7L1"],
		endure: ["7L1"],
		facade: ["7L48", "7M"],
		fly: ["7M"],
		focuspunch: ["7M"],
		heartbreak: ["7M"],
		heatclaw: ["7L1"],
		mindbomb: ["7M"],
		mirrorcoat: ["7L1"],
		protect: ["7M"],
		psychic: ["7M"],
		psychup: ["7L1"],
		raindance: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		roost: ["7L36"],
		safeguard: ["7L27", "7M"],
		secretpower: ["7M"],
		skyattack: ["7L1", "7L52"],
		sleeptalk: ["7L1"],
		snatch: ["7M"],
		soar: ["7L30"],
		steelwing: ["7M"],
		substitute: ["7L1"],
		sunnyday: ["7M"],
		swagger: ["7M"],
		thief: ["7M"],
		toxic: ["7M"],
		trazorwind: ["7M"],
		tslash: ["7L40"],
		whirlwind: ["7L1"],
		zenheadbutt: ["7L33"],
	}},
	tensoku: {learnset: {
		attract: ["7M"],
		blazekick: ["7L43"],
		blizzard: ["7M"],
		brickbreak: ["7M"],
		bulkup: ["7L50"],
		calmmind: ["7M"],
		decision: ["7M"],
		doubleteam: ["7M"],
		earthquake: ["7M"],
		explosion: ["7L1", "7L62"],
		fireblast: ["7M"],
		firepunch: ["7L1"],
		flamethrower: ["7M"],
		fly: ["7L1", "7L58", "7M"],
		focusblast: ["7M"],
		focuspunch: ["7M"],
		gigadrain: ["7M"],
		icebeam: ["7M"],
		icepunch: ["7L1"],
		irondefense: ["7L40"],
		overheat: ["7L37"],
		poisonjab: ["7M"],
		protect: ["7M"],
		raindance: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		rocksmash: ["7M"],
		safeguard: ["7M"],
		secretpower: ["7M"],
		selfdestruct: ["7L1"],
		skillswap: ["7M"],
		solarbeam: ["7M"],
		steelfist: ["7M"],
		substitute: ["7L1"],
		sunnyday: ["7M"],
		superpower: ["7L1"],
		surf: ["7M"],
		swagger: ["7M"],
		taunt: ["7M"],
		tflash: ["7M"],
		thunder: ["7M"],
		thunderbolt: ["7M"],
		thunderpunch: ["7L1"],
		thunderwave: ["7L46"],
		tmeteormash: ["7L1", "7L54"],
		tstrength: ["7M"],
		trazorwind: ["7M"],
		waterpulse: ["7M"],
	}},
	attacksanae: {learnset: {
		attract: ["7M"],
		calmmind: ["7M"],
		decision: ["7M"],
		doubleteam: ["7M"],
		endure: ["7L43"],
		gigadrain: ["7M"],
		grassknot: ["7L1"],
		icywind: ["7L1"],
		imprison: ["7L46"],
		ingrain: ["7L1"],
		mirrorcoat: ["7L1"],
		muddywater: ["7L40"],
		protect: ["7M"],
		raindance: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		safeguard: ["7M"],
		secretpower: ["7M"],
		skillswap: ["7M"],
		solarbeam: ["7M"],
		surf: ["7M"],
		swagger: ["7M"],
		taunt: ["7L50", "7M"],
		textrasensory: ["7L37"],
		tflash: ["7M"],
		thunder: ["7L1", "7L54", "7M"],
		trazorwind: ["7M"],
		tsilverwind: ["7L1", "7L58"],
		waterpulse: ["7M"],
		waterspout: ["7L1", "7L62"],
		wish: ["7L1"],
	}},
	technicalsanae: {learnset: {
		attract: ["7M"],
		calmmind: ["7L46", "7M"],
		decision: ["7M"],
		doubleteam: ["7M"],
		dragondance: ["7L40"],
		encore: ["7L1", "7L54"],
		energyball: ["7L43"],
		gigadrain: ["7M"],
		grassknot: ["7L1"],
		icywind: ["7L1"],
		ingrain: ["7L1"],
		megadrain: ["7L1", "7L58"],
		mirrorcoat: ["7L1"],
		protect: ["7M"],
		raindance: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		safeguard: ["7M"],
		secretpower: ["7M"],
		skillswap: ["7M"],
		solarbeam: ["7M"],
		surf: ["7M"],
		swagger: ["7M"],
		taunt: ["7M"],
		textrasensory: ["7L37"],
		tflash: ["7M"],
		thunder: ["7M"],
		trazorwind: ["7M"],
		tsilverwind: ["7L1", "7L62"],
		waterpulse: ["7M"],
		wish: ["7L50"],
	}},
	technicalsatori: {learnset: {
		amnesia: ["7L1", "7L52"],
		attract: ["7M"],
		blizzard: ["7M"],
		calmmind: ["7M"],
		counter: ["7L1"],
		curse: ["7M"],
		darkpulse: ["7L42"],
		decision: ["7M"],
		destinybond: ["7L1", "7L64"],
		disable: ["7L39"],
		doubleteam: ["7M"],
		earthquake: ["7L48", "7M"],
		feint: ["7L1"],
		focusblast: ["7M"],
		icebeam: ["7M"],
		ingrain: ["7L1"],
		jamming: ["7L1"],
		lightscreen: ["7M"],
		mindbomb: ["7M"],
		mirrorcoat: ["7L1"],
		nightshade: ["7L1"],
		protect: ["7M"],
		psychic: ["7M"],
		psychup: ["7L1"],
		raindance: ["7M"],
		reflect: ["7M"],
		rest: ["7M"],
		return: ["7M"],
		safeguard: ["7M"],
		screech: ["7L45"],
		secretpower: ["7M"],
		selfdestruct: ["7L1"],
		skillswap: ["7M"],
		substitute: ["7L1"],
		sunnyday: ["7M"],
		thunder: ["7M"],
		thunderbolt: ["7M"],
		tlusterpurge: ["7L1", "7L60"],
		tmistball: ["7L1", "7L56"],
		tsignalbeam: ["7M"],
		willowisp: ["7M"],
	}},
	defensesatori: {learnset: {
		charm: ["7L45"],
		counter: ["7L40"],
		destinybond: ["7L50"],
		encore: ["7L45"],
		mirrorcoat: ["7L40"],
	}},
};