'use strict';

exports.BattlePokedex = {
	////////////////////////////////////
	// TPPLeague Fakemon (Dex Number = (-152)~(-190))
	////////////////////////////////////
	gumblegoose: {
		num: -152,
		species: "Gumblegoose",
		types: ["Water", "Flying"],
		gender: "N",
		baseStats: {hp: 70, atk: 35, def: 95, spa: 135, spd: 55, spe: 135},
		abilities: {0: "Lightning Rod"},
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	
	////////////////////////////////////
	// Prism Fakemon (Dex Number = 9000+)
	////////////////////////////////////
	phancero: {
		num: 9001,
		species: "Phancero",
		types: ["Ghost", "Flying"],
		gender: "N",
		baseStats: {hp: 178, atk: 137, def: 57, spa: 85, spd: 65, spe: 128},
		abilities: {0: "Download", 1: "Contrary"},
		heightm: 1.5,
		weightkg: 46.8,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},

	////////////////////////////////////
	// Gen 1 Glitchmon (Dex Number = (-191)~(-255))
	////////////////////////////////////
	rb202: {
		num: -202,
		species: "RB:202",
		types: ["Nοrmal", "Grοund"],
		gender: "N",
		baseStats: {hp: 232, atk: 147, def: 145, spa: 136, spd: 136, spe: 128},
		abilities: {0: ""},
		heightm: 66.1,
		weightkg: 975.3,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},

	////////////////////////////////////
	// Touhoumon (Dex Number = 20000+)
	////////////////////////////////////
	chibisanae: {
		num: 20001,
		species: "Chibi Sanae",
		types: ["Dragon"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65, atk: 35, def: 90, spa: 55, spd: 90, spe: 45},
		abilities: {0: "Serene Grace"},
		heightm: 0.4,
		weightkg: 20,
		color: "White",
		evos: ["sanae", "attacksanae", "technicalsanae", "tensoku"],
		eggGroups: ["Humanshape"],
	},
	sanae: {
		num: 20002,
		species: "Sanae",
		types: ["Dragon", "Electric"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 90, atk: 60, def: 115, spa: 80, spd: 115, spe: 70},
		abilities: {0: "Serene Grace"},
		heightm: 0.6,
		weightkg: 60,
		color: "White",
		prevo: "chibisanae",
		evoLevel: 36,
		eggGroups: ["Humanshape"],
	},
	chibimomiji: {
		num: 20011,
		species: "Chibi Momiji",
		types: ["Rock"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 65, atk: 80, def: 70, spa: 25, spd: 25, spe: 65},
		abilities: {0: "Run Away", 1: "Early Bird"},
		heightm: 0.7,
		weightkg: 5,
		color: "Gray",
		evos: ["momiji", "defensemomiji"],
		eggGroups: ["Humanshape", "Field"],
	},
	momiji: {
		num: 20012,
		species: "Momiji",
		types: ["Rock", "Steel"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80, atk: 130, def: 80, spa: 50, spd: 50, spe: 90},
		abilities: {0: "Intimidate", 1: "Guts"},
		heightm: 1.1,
		weightkg: 20,
		color: "Gray",
		prevo: "chibimomiji",
		evoLevel: 28,
		eggGroups: ["Humanshape", "Field"],
	},
	chibitokiko: {
		num: 20021,
		species: "Chibi Tokiko",
		types: ["Flying"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 70, atk: 55, def: 70, spa: 30, spd: 60, spe: 45},
		abilities: {0: "Limber", 1: "Early Bird"},
		heightm: 0.3,
		weightkg: 1,
		color: "Black",
		evos: ["tokiko", "attacktokiko"],
		eggGroups: ["Humanshape", "Flying"],
	},
	tokiko: {
		num: 20022,
		species: "Tokiko",
		types: ["Flying"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 100, atk: 80, def: 100, spa: 40, spd: 90, spe: 70},
		abilities: {0: "Limber", 1: "Early Bird"},
		heightm: 1.2,
		weightkg: 12,
		color: "Black",
		prevo: "chibitokiko",
		evoLevel: 25,
		eggGroups: ["Humanshape", "Flying"],
	},
	defensemomiji: {
		num: 20246,
		species: "Defense Momiji",
		types: ["Rock", "Steel"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 100, atk: 70, def: 115, spa: 40, spd: 90, spe: 65},
		abilities: {0: "Sand Veil", 1: "Early Bird"},
		heightm: 1,
		weightkg: 20,
		color: "Gray",
		prevo: "chibimomiji",
		evoLevel: 1,
		eggGroups: ["Humanshape", "Field"],
	},
	attacktokiko: {
		num: 20280,
		species: "Attack Tokiko",
		types: ["Flying"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80, atk: 100, def: 70, spa: 40, spd: 70, spe: 120},
		abilities: {0: "Limber", 1: "Guts"},
		heightm: 1,
		weightkg: 10,
		color: "Black",
		prevo: "chibitokiko",
		evoLevel: 1,
		eggGroups: ["Humanshape", "Flying"],
	},
	tensoku: {
		num: 20289,
		species: "Tensoku",
		types: ["Steel", "Fire"],
		gender: "N",
		baseStats: {hp: 90, atk: 110, def: 180, spa: 60, spd: 60, spe: 50},
		abilities: {0: "Shed Skin"},
		heightm: 1,
		weightkg: 150,
		color: "Red",
		prevo: "chibisanae",
		evoLevel: 1,
		eggGroups: ["Humanshape", "Field"],
	},
	attacksanae: {
		num: 20309,
		species: "Attack Sanae",
		types: ["Dragon", "Water"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 80, atk: 70, def: 80, spa: 130, spd: 80, spe: 90},
		abilities: {0: "Serene Grace"},
		heightm: 1,
		weightkg: 60,
		color: "White",
		prevo: "chibisanae",
		evoLevel: 1,
		eggGroups: ["Humanshape"],
	},
	technicalsanae: {
		num: 20310,
		species: "Technical Sanae",
		types: ["Dragon", "Grass"],
		genderRatio: {M: 0.5, F: 0.5},
		baseStats: {hp: 90, atk: 60, def: 85, spa: 105, spd: 80, spe: 110},
		abilities: {0: "Serene Grace"},
		heightm: 1,
		weightkg: 60,
		color: "White",
		prevo: "chibisanae",
		evoLevel: 1,
		eggGroups: ["Humanshape"],
	},
};
